on:
  push:
    branches:
      - master
      - 2.26.0

env:
  ACTIVE_API_URL: "https://prod-demo1.nnsworkshop.com/active"
  ACTIVE_REGISTRY_URL: "jfrog.cicd.nonamesec.com/nns-docker"
  #ACTIVE_BACKEND_URI: "prod-demo1.nnsworkshop.com/active/backend"

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Run VAmPI
         run: docker compose up -d

       - name: Test VAmPI
         run: sleep 5 && curl http://localhost:5002/ --retry 10 --retry-delay 1

       - name: Docker login
         uses: docker/login-action@v1
         with:
          registry: ${{ env.ACTIVE_REGISTRY_URL }}
          username: ${{ secrets.ACTIVE_REGISTRY_USER }}
          password: ${{ secrets.ACTIVE_REGISTRY_PASSWORD }}

       #-e ACTIVE_BACKEND_URI=${{ env.ACTIVE_BACKEND_URI }}
       #${{ env.ACTIVE_REGISTRY_URL }}/active-cli:$(curl -k ${{env.ACTIVE_API_URL}}/backend/version) scan
       - name: Active Testing Scan
         run: >
          docker run
          --add-host=host.docker.internal:host-gateway
          -e ACTIVE_CONFIG_FILE_PATH=/noname/active-config_vampi.json
          -v $(pwd)/noname:/noname
          ${{ env.ACTIVE_REGISTRY_URL }}/active-cli:2.26.0 scan
          --api-url=${{ env.ACTIVE_API_URL }}
          --api-token=${{ secrets.ACTIVE_API_TOKEN }}
          --test-group-id=9cfa523e-8154-4673-b947-945cc44d1f8f
          --branch-name=${{ github.head_ref || github.ref_name }}
          --severity-threshold=none

  deploy:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo Security scan passed, deploying to production

